# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ipText = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ipText.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhUrlCharactersOnly)
        self.ipText.setObjectName("ipText")
        self.horizontalLayout.addWidget(self.ipText)
        self.connectButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.connectButton.setEnabled(True)
        self.connectButton.setCheckable(False)
        self.connectButton.setChecked(False)
        self.connectButton.setDefault(False)
        self.connectButton.setFlat(False)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout.addWidget(self.connectButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.graph = QtWidgets.QHBoxLayout()
        self.graph.setObjectName("graph")
        self.verticalLayout.addLayout(self.graph)
        self.textLog = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textLog.setObjectName("textLog")
        self.verticalLayout.addWidget(self.textLog)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.messageText = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.messageText.setEnabled(False)
        self.messageText.setText("")
        self.messageText.setClearButtonEnabled(True)
        self.messageText.setObjectName("messageText")
        self.horizontalLayout_2.addWidget(self.messageText)
        self.sendButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sendButton.setEnabled(False)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout_2.addWidget(self.sendButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stranded In Space"))
        self.ipText.setPlaceholderText(_translate("MainWindow", "IP"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.messageText.setPlaceholderText(_translate("MainWindow", "Message"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
